OIQS/mcq_v2/editor/urls.py
from django import urls
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('',views.index),
    ]

OIQS/mcq_v2/mcq_v2/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import RemoveQuiz,information,EditStudent,EditTeacher,AddtoList,DeleteQuestion,EditQuestion,AddQuestion,AddQuiz,deleteQuiz,editQuiz,index,login_view,signup,instruction,dashboard,leaderboard,logout_view,result,teacher



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('signup/',signup),
    path('login/',login_view),
    path('logout/',logout_view,name="logout"),
    path('information/',information,name="information"),
    path('leaderboard/',leaderboard),
    path('teacher/',teacher),
    path('editteacher/',EditTeacher,name="EditTeacher"),
    path('editstudent/',EditStudent,name="EditStudent"),

    #quiz
    path('instruction/<int:id>',instruction, name="AttemptQuiz"),
    path('RemoveQuiz/<int:id>',RemoveQuiz,name="RemoveQuiz"),
    path('dashboard/<int:id>',dashboard,name="dashboard"),
    path('result/<int:id>',result,name="result"),
    path('addQuiz',AddQuiz,name="addQuiz"),
    path('editQuiz/<int:id>',editQuiz,name="editQuiz"),
    path('deleteQuiz/<int:id>',deleteQuiz,name="deleteQuiz"),
    path('AddtoList/<int:id>',AddtoList,name="AddtoList"),

    #question
    path('addQuestion',AddQuestion,name="AddQuestion"),
    path('EditQuestion/<int:id1>/<int:id2>',EditQuestion,name="EditQuestion"),
    path('DeleteQuestion/<int:id1>/<int:id2>',DeleteQuestion,name="DeleteQuestion"),
    # path('email/',include('sendemail.urls')),
    #path('contact/',include('contactus.urls')),
    # path('theory/',include('theory.urls')),
    # path('editor/',include('editor.urls')),
    # path('compiler/',include('mycompiler.urls')),
    #path('theory/<int:id>',include('theory.urls')),
]

OIQS/mcq_v2/teacher/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from django.contrib.auth import get_user_model

User=get_user_model()

# Create your models here.

class tprofile(models.Model):
	CHOICES= [
    ('CS', 'Computer Science'),
    ('IT', 'Information Technology'),
    ('Civil', 'Civil'),
    ('Mechanical', 'Mechanical'),
    ('EC', 'Electronics & Communication'),
    ('EEE', 'Electrical & Electronics Engg.'),
    ('EE', 'Electrical Engg.'),
    ('IC', 'Instrumentation & Control Engg.'),
    ]
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	name=models.CharField(max_length=255)
	college=models.CharField(max_length=255)
	branch=models.CharField(max_length=255,choices=CHOICES,default=True)
	year=models.PositiveIntegerField(default=1,validators=[MinValueValidator(1),MaxValueValidator(4)])
	contact=models.CharField(null=True,blank=True,max_length=10)
	status=models.CharField(max_length=255,choices=[('Student','Student'),('Teacher','Teacher')])

	def __str__(self):
		return self.name

OIQS/mcq_v2/teacher/views.py
from django.shortcuts import render

# Create your views here.

OIQS/mcq_v2/templates/teacher/AddQuestion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Question</title>
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/mdb.min.css' %}" rel="stylesheet">
</head>
<body style="
color: white;
background-color: #212529;
">
<br>
  <div class="container" id="dione">
  <form method='POST'>
    {% csrf_token %}
    <div class="row mb-3">
      <label for="ques_id" class="col-sm-2 col-form-label">Ques id:</label>
      <div class="col-sm-10">
        <input name="ques_id" type="number" class="form-control" id="inputid">
      </div>
    </div>
    <div class="row mb-3">
      <label for="ques_title" class="col-sm-2 col-form-label">Question Title:</label>
      <div class="col-sm-10">
        <input name="ques_title" type="text" class="form-control" id="inputTitle">
      </div>
    </div>
    <div class="row mb-3">
      <label for="ques_desc" class="col-sm-2 col-form-label">Desc:</label>
      <div class="col-sm-10 form-outline">
        <textarea name="ques_desc" class="form-control" id="textareaDesc" rows="5"style="height: fit-content;"></textarea>
      </div>
    </div>
    <div class="row mb-3">
        <label for="option1" class="col-sm-2 col-form-label">Option 1:</label>
        <div class="col-sm-10">
          <input name="option1" type="text" class="form-control" id="option1">
        </div>
    </div>
    <div class="row mb-3">
        <label for="option2" class="col-sm-2 col-form-label">Option 2:</label>
        <div class="col-sm-10">
          <input name="option2" type="text" class="form-control" id="option2">
        </div>
    </div>
    <div class="row mb-3">
        <label for="option3" class="col-sm-2 col-form-label">Option 3:</label>
        <div class="col-sm-10">
          <input name="option3" type="text" class="form-control" id="option3">
        </div>
    </div>
    <div class="row mb-3">
        <label for="option4" class="col-sm-2 col-form-label">Option 4:</label>
        <div class="col-sm-10">
          <input name="option4" type="text" class="form-control" id="option4">
        </div>
    </div>
    <div class="row mb-3">
        <label for="correct_option" class="col-sm-2 col-form-label">Correct Option:</label>
        <div class="col-sm-10">
          <input name="correct_option" type="number" class="form-control" id="correct_option">
        </div>
      </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>
</body>
</html>

OIQS/mcq_v2/templates/teacher/AddQuiz.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Quiz</title>
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
</head>
<body style="color: white;background-color: #212529;">
    <br>
  <div class="container" id="dione">
    <form method="POST" id="AddQuizForm">
        {% csrf_token %}
        <div class="row mb-3">
          <label for="input_title" class="col-sm-2 col-form-label">Quiz Title:</label>
          <div class="col-sm-10">
            <input placeholder="Enter title" name="quiz_title" type="text" class="form-control" id="inputTitle">
          </div>
        </div>
        <div class="row mb-3">
          <label for="input_time" class="col-sm-2 col-form-label">Quiz Time:</label>
          <div class="col-sm-10">
            <input placeholder="Enter time in minutes" name="quiz_time" type="number" class="form-control" id="inputTime">
          </div>
        </div>
        <fieldset class="row mb-3">
          <legend class="col-form-label col-sm-2 pt-0">Questions:</legend>
          <div class="col-sm-10">
            <select name="questions" id="lang" multiple>
                {% for question in quesset %}
                    <option value={{question.pk}}>{{question.title}}</option>
                {% endfor %}
            </select>
          </div>
        </fieldset>
        <div class="row mb-3">
          <div class="col-sm-10 offset-sm-2">
            <div class="form-check">
                <button value="open" onClick="AddQuestionWindow()" type="button" class="btn btn-outline-primary btn-sm">Add New Question</button>
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
      </form>
      <script type="text/javascript">  
        function AddQuestionWindow()  
        {  
           window.open("{% url 'AddQuestion' %}","Add Question","top=50,left=400,toolbar=no,status=no,menubar=no,location=right,scrollbars=yes,resizable=yes,height=750,width=800");  
        }  
     </script>  
    </div>
</body>
</html>

OIQS/mcq_v2/templates/teacher/EditQuestion.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Question</title>
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/mdb.min.css' %}" rel="stylesheet">
</head>
<body style="
color: white;
background-color: #212529;
">
  <br>
  <div class="container" id="dione">
  <form method='POST'>
    {% csrf_token %}
    <div class="row mb-3">
      <label for="ques_id" class="col-sm-2 col-form-label">Ques id:</label>
      <div class="col-sm-10">
        <input value="{{Question.qus_id}}" name="ques_id" type="number" class="form-control" id="inputid">
      </div>
    </div>
    <div class="row mb-3">
      <label for="ques_title" class="col-sm-2 col-form-label">Question Title:</label>
      <div class="col-sm-10">
        <input value="{{Question.title}}" name="ques_title" type="text" class="form-control" id="inputTitle">
      </div>
    </div>
    <div class="row mb-3">
      <label for="ques_desc" class="col-sm-2 col-form-label">Desc:</label>
      <div class="col-sm-10">
        <textarea name="ques_desc" class="form-control" id="textareaDesc" rows="5" style="height: fit-content;">{{Question.desc}}</textarea>
      </div>
    </div>
    <div class="row mb-3">
        <label for="option1" class="col-sm-2 col-form-label">Option 1:</label>
        <div class="col-sm-10">
          <input value="{{Question.option_1}}" name="option1" type="text" class="form-control" id="option1">
        </div>
    </div>
    <div class="row mb-3">
        <label for="option2" class="col-sm-2 col-form-label">Option 2:</label>
        <div class="col-sm-10">
          <input value="{{Question.option_2}}" name="option2" type="text" class="form-control" id="option2">
        </div>
    </div>
    <div class="row mb-3">
        <label for="option3" class="col-sm-2 col-form-label">Option 3:</label>
        <div class="col-sm-10">
          <input value="{{Question.option_3}}" name="option3" type="text" class="form-control" id="option3">
        </div>
    </div>
    <div class="row mb-3">
        <label for="option4" class="col-sm-2 col-form-label">Option 4:</label>
        <div class="col-sm-10">
          <input value="{{Question.option_4}}" name="option4" type="text" class="form-control" id="option4">
        </div>
    </div>
    <div class="row mb-3">
        <label for="correct_option" class="col-sm-2 col-form-label">Correct Option:</label>
        <div class="col-sm-10">
          <input value="{{Question.correct_option}}" name="correct_option" type="number" class="form-control" id="correct_option">
        </div>
      </div>
    <button onClick="refreshAndClose()" type="submit" id="myform" class="btn btn-primary">Save</button>
  </form>
  <script type="text/javascript">
  function refreshAndClose() {
      window.opener.location.reload();
      document.getElementById("myform").submit();
      window.close();
    }
  </script>
</div>
</body>
</html>

OIQS/mcq_v2/templates/teacher/EditTeacher.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Teacher</title>
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
</head>
<body style="
color: white;
background-color: #212529;
">
    <br>
  <div class="container" id="dione">

    <h1>Update Details:</h1><br>
    <form method="POST" id="EditTeacherForm">
        {% csrf_token %}
        <div class="row mb-3">
          <label for="input_name" class="col-sm-2 col-form-label">Name:</label>
          <div class="col-sm-10">
            <input value="{{Teacher.name}}" name="Tname" type="text" class="form-control" id="inputName">
          </div>
        </div>
        <div class="row mb-3">
          <label for="input_college" class="col-sm-2 col-form-label">College:</label>
          <div class="col-sm-10">
            <input value="{{Teacher.college}}" name="Tcollege" type="text" class="form-control" id="inputCollege">
          </div>
        </div>
        <div class="row mb-3">
          <label for="input_branch" class="col-sm-2 col-form-label">Branch:</label>
          <div class="col-sm-10">
            <select name="Tbranch" class="form-control" id="exampleFormControlSelect1">
                {% for branch in branchlist %}
                <option value="{{branch.0}}">{{branch.1}}</option>
                {% endfor %}
            </select>
          </div>
        </div>
        <div class="row mb-3">
            <label for="input_year" class="col-sm-2 col-form-label">Year:</label>
            <div class="col-sm-10">
              <input max="4" min="1" value="{{Teacher.year}}" name="Tyear" type="number" class="form-control" id="inputYear">
            </div>
        </div>
        <div class="row mb-3">
            <label for="input_contact" class="col-sm-2 col-form-label">Contact:</label>
            <div class="col-sm-10">
              <input value="{{Teacher.contact}}" name="Tcontact" type="text" class="form-control" id="inputContact">
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-sm-10">
                <label for="submit_button" class="col-sm-2 col-form-label"></label>
                <button onClick="window.opener.location.reload()" type="submit" class="btn btn-primary">Save</button>
            </div>   
        </div>
    </form>

    <script type="text/javascript">  
        function AddQuestionWindow()  
        {  
           window.open("{% url 'AddQuestion' %}","Add Question","top=50,left=500,toolbar=no,status=no,menubar=no,location=right,scrollbars=yes,resizable=yes,height=700,width=600");  
        }
    </script>  
  </div>
</body>
</html>

OIQS/mcq_v2/templates/teacher/editQuiz.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Quiz</title>
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
</head>
<body style="color: white;background-color: #212529;">
    <br>
  <div class="container" id="dione">
    
    <form method="POST" id="AddQuizForm">
        {% csrf_token %}
        <div class="row mb-3">
          <label for="input_title" class="col-sm-2 col-form-label">Quiz Title:</label>
          <div class="col-sm-10">
            <input value="{{Quiz.title}}" name="quiz_title" type="text" class="form-control" id="inputTitle">
          </div>
        </div>
        <div class="row mb-3">
          <label for="input_time" class="col-sm-2 col-form-label">Quiz Time:</label>
          <div class="col-sm-10">
            <input value="{{Quiz.time}}" name="quiz_time" type="number" class="form-control" id="inputTime" placeholder="Enter time in minutes">
          </div>
        </div>
        <div class="row mb-3">
          <legend class="col-form-label col-sm-2 pt-0">Questions:</legend>
          <div class="col-sm-10">
            <table class="table table-dark table-striped" style="border: 1px solid;">
                <thead>
                  <tr>
                    <th scope="col">S.no</th>
                    <th scope="col">Question Name</th>
                    <th scope="col">Edit Question</th>
                    <th scope="col">Remove</th>
                  </tr>
                </thead>
                <tbody>
                  {% for question in quizQ %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{question.title}}</td>
                        <td><button value="Open" onClick="window.open('{% url 'EditQuestion' Quiz.pk question.pk %}','Edit Question','top=50,left=500,toolbar=no,status=no,menubar=no,location=center,scrollbars=yes,resizable=yes,height=700,width=600')" type="button" class="btn btn-warning btn-sm">edit</button></td>
                        <td><a href="{% url 'DeleteQuestion' Quiz.pk question.pk %}"><button value="Open" type="button" class="btn btn-danger btn-sm">remove</button></td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
          </div>
        </div>
        <div class="row mb-3">
            <legend class="col-form-label col-sm-2 pt-0">Add Questions:</legend>
            <div class="col-sm-10">
                <select name="questions" id="lang" multiple>
                    {% for question in quesset %}
                    <option value="{{question.pk}}">{{question.title}}</option>
                    {% endfor %}
                </select>
                <button name="Add" value="AddtoList" type="submit" class="btn btn-outline-info btn-sm">Add to List</button>
                <div class="row mb-3">
                  <div class="col-sm-10">
                    <button value="open" onClick="AddQuestionWindow()" type="button" class="btn btn-outline-primary btn-sm">Add New Question</button>
                    <button name="Delete" value="DeleteQuestions" type="submit" class="btn btn-outline-danger btn-sm">Delete Questions</button>
                  </div>
                </div>
            </div>
          </div>
        <button onClick="window.location.reload(true)"type="submit" class="btn btn-primary">Save</button>
    </form>
      <script type="text/javascript">  
        function AddQuestionWindow()  
        {  
           window.open("{% url 'AddQuestion' %}","Add Question","top=50,left=400,toolbar=no,status=no,menubar=no,location=right,scrollbars=yes,resizable=yes,height=750,width=800");  
        }
     </script>  
    </div>
</body>
</html>

OIQS/mcq_v2/templates/teacher/teacher.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Teacher</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
  <link rel="icon" href="{% static 'assets/img/logo.png' %}">
  <link href="{% static 'assets/css/dashboard1.css' %}" rel="stylesheet">
</head>

<body class="fixed-sn animated fadeIn" style="
background-color: #2E2E2E;">

    <header>
    <nav class="navbar navbar-expand-lg navbar-dark elegant-color">
        <div class="navbar-brand" title="PIET Website"><img src="{% static 'assets/img/logo.png' %}">
        <p id="head">PIET KNOWLEDGE</p>
        </div>
        {% if user.is_authenticated %}
        <ul class="nav navbar-nav nav-flex-icons ml-auto">
        <li class="nav-item">
            <a href="/logout" class="nav-link">
            <i class="fa fa-sign-out"></i>
            <span class="clearfix d-none d-sm-inline-block">Sign Out</span>
            </a>
        </li>
        </ul>
        {% else %}
        <ul class="nav navbar-nav nav-flex-icons ml-auto">
        <li class="nav-item">
            <a href="/login" class="nav-link">
            <i class="fa fa-sign-out"></i>
            <span class="clearfix d-none d-sm-inline-block">Login</span>
            </a>
        </li>
        </ul>
        {% endif %}
    </nav>
    </header>
    {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="True">&times;</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
    <table class="table table-hover table-dark">
      <thead class="thead-dark">
        <tr>
          <th scope="colgroup" colspan="2"><b>Your Details:</b> &nbsp&nbsp&nbsp <button value="Open" onClick="window.open('{% url 'EditTeacher' %}','Add Quiz','toolbar=no,status=no,menubar=no,location=center,scrollbars=yes,resizable=yes,height=650,width=400')" type="button" class="btn btn-outline-warning btn-sm">update</button></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"><b>Name:</th>
          <td>{{Teacher.name}}</td>
        </tr>
        <tr>
          <th scope="row"><b>College:</th>
          <td>{{Teacher.college}}</td>
        </tr>
        <tr>
          <th scope="row"><b>Branch:</th>
          <td>{{Teacher.get_branch_display}}</td>
        </tr>
        <tr>
          <th scope="row"><b>Year:</th>
          <td>{{Teacher.year}}</td>
        </tr>
        <tr>
          <th scope="row"><b>Contact:</th>
          <td>{{Teacher.contact}}</td>
        </tr>
        <tr>
          <th scope="row"><b>Status:</th>
          <td>{{Teacher.get_status_display}}</td>
        </tr>
      </tbody>
    </table>
    <hr>
    <table class="table table-dark table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th scope="colgroup" colspan="5"><b>Active Quizzes: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<button value="Open" onClick="AddQuizWindow()" type="button" class="btn btn-outline-primary btn-sm">Add Quiz</button></th>
        </tr>
        <tr>
          <th scope="col"><b>S.no</th>
          <th scope="col"><b>Quiz Name</th>
          <th scope="col"><b>No. of Questions</th>
          <th scope="col"><b>Update Quiz</th>
          <th scope="col"><b>Delete Quiz</th>
        </tr>
      </thead>
      <tbody>
        {% for quiz, ques in multivalue %}
          <tr>
              <th scope="row"><b>{{forloop.counter}}</th>
              <td>{{quiz.title}}</td>
              <td>{{ques}}</td>
              <td><button value="Open" onClick="window.open('{% url 'editQuiz' quiz.pk %}','Add Quiz','toolbar=no,top=100,left=250,status=no,menubar=no,location=center,scrollbars=yes,resizable=yes,height=650,width=1000')" type="button" class="btn btn-warning btn-sm btn-rounded">edit</button></td>
              <td><a href="{% url 'deleteQuiz' quiz.pk %}"><button value="Open" type="button" class="btn btn-danger btn-rounded btn-sm">DELETE</button></a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>



    <footer class="page-footer elegant-color center-on-small-only">
        <div class="footer-copyright">
          <div class="container-fluid">
            © 2023 Copyright:
            <a href="#">PIET Innovations</a>
    
          </div>
        </div>
      </footer>
    
      <script type="text/javascript" src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'assets/js/popper.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'assets/js/mdb.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'assets/js/dashboard1.js' %}"></script>
      <script type="text/javascript">  
        function AddQuizWindow()  
        {  
           window.open("{% url 'addQuiz' %}","Add Quiz","top=130,left=550,toolbar=no,status=no,menubar=no,location=center,scrollbars=yes,resizable=yes,height=530,width=450");  
        }  
     </script>  
</body>
</html>